### ISSUE TITLE
Update Discord RPC

### ISSUE THREAD

**Issue by frissyn** [replit-discord/repl-it-electron#100]
I'd like to add something similar to how the [un]official VSC plugin handles Discord RPC, with icons of the language you're currently coding in being the icon shows. 

Also, there needs to be a way to detect is a REPL is private or not, so it doesn't show in the RPC.

I'll work on this when I can

**Comment by CoolCoderSJ** [comment]
https://github.com/vscode-icons/vscode-icons/tree/master/icons

(Vscode icons link for safekeeping)
I've also added the link in the todo board.

**Comment by JDOG787** [comment]
I would like to help with this too, bc this is why i got the app in the first place lol

**Comment by frissyn** [comment]
Added a progress tracker on the Trello Board, got some stuff done yesterday.

https://trello.com/c/d7OWx4sH/4-update-discord-rpc

**Comment by spotandjake** [comment]
You need to make the app not error when discord is not installed.
