### ISSUE TITLE
Multimonitor support

### ISSUE THREAD

**Issue by spotandjake** [replit-discord/repl-it-electron#102]
Multi-monitor to have the console on one screen and the ide on another.

**Comment by alanlichen** [comment]
Will definitely be very useful. Could you make it like Roblox studio's thing where you can separate the parts with a double click, then you can drag them everywhere?

**Comment by JDOG787** [comment]
Hey @spotandjake Leon said I could do this. Is that ok?

**Comment by spotandjake** [comment]
totally just do you want to work on this one together also not to mention the fact that when we do this we should implement things like being able to close the vnc and open it again and all that as it should be pretty easy if we are already doing the console.

**Comment by JDOG787** [comment]
wdym by vnc @spotandjake?

**Comment by spotandjake** [comment]
The graphics window

**Comment by JDOG787** [comment]
ah ok
