### ISSUE TITLE
"git" is not working in Windows.

### ISSUE THREAD

**Issue by DaMammoth** [replit-discord/repl-it-electron#137]
I am trying to install the application, using the instructions listed in the description; but when I use the command "git" on the Node command prompt, I get Windows's `'git' is not recognized as an internal or external command,
operable program or batch file.` error message. What am I doing wrong?

┆Issue is synchronized with this [Trello card](https://trello.com/c/ufWWZgv7) by [Unito](https://www.unito.io/learn-more)

**Comment by leon332157** [comment]
You need to either install git command line from https://git-scm.com or use GitHub Desktop: desktop.github.com

**Comment by CoolCoderSJ** [comment]
Also note that the git commands are for experimental releases, and you may experience a ton of bugs. For a more stable release, click the releases tab on the right, and download the v2 installer.

**Comment by leon332157** [comment]
Closed for inactivity.
