### ISSUE TITLE
Theme not shown

### ISSUE THREAD

**Issue by whippingdot** [replit-discord/repl-it-electron#140]
The theme is not shown if you open something in a new window. The theme that is there instead is the theme repl.it has assigned you or the theme you had originally without the reflux being activated. By new window I mean if you hold control and click on one of the links it opens in a new window and there, there is no active reflux theme being used. I hope this can get fixed soon.

Not related to the this, but a feature request: I think you should add a custom settings button on top of the repl.it website from which you can access the theme switching, and everything else you can access by press the top bar. This would be better as you can have your own custom CSS, and people who are using this for the first time can at least know that there is an option like that as they would see the gear icon or whatever at the bottom right and if they pressed that they could see the settings. Using this you can also have more options, like hiding the settings and instead making it a sidebar, or something like that.

P.S. I haven't proof read this so if you have a doubt comment

**Comment by spotandjake** [comment]
Fixed the theme issue, it was a rather simple oversight. we will add a custom setting area but that requires a bit of a change so i do not know if it will make it into this version. i am closing this issue as well.

**Comment by whippingdot** [comment]
Thanks, i can close the issue cause the main reason I opened it was for the bug you fixed. The other thing is not a major one. Add this as a not on the ROADMAP tho
