### ISSUE TITLE
Theming / Theming Market place

### ISSUE THREAD

**Issue by frissyn** [replit-discord/repl-it-electron#98]
We can add this to the `To-Do` list or whatever, but I'd like to see [Reflux Themes](https://github.com/frissyn/Reflux) be integrated into the app. Instead of bookmarklets, they can be options in a custom menu that you can pick and choose. Users should be able to add their own themes, and the theme should persist across sessions.

I'll work on this when you guys finish reworking the base structure.

**Comment by CoolCoderSJ** [comment]
I made this
https://reflux-marketplace.coolcodersj.repl.co/
idk if you guys wanna somehow integrate that

**Comment by frissyn** [comment]
@CoolCoderSJ ok thanks, I'll take a look

**Comment by JDOG787** [comment]
Yea we should have a theme market place

**Comment by JDOG787** [comment]
And then have themes be built into the app more

**Comment by frissyn** [comment]
Ok sure

**Comment by spotandjake** [comment]
yes where you can import a normal reflux theme. and add to the market place it would be nice if the market place was availble online as well so that people can use the themes in both places.

**Comment by CoolCoderSJ** [comment]
the marketplace is available online, but u might wanna write a custom client for the api (That jdog and i are later gonna build) so that there's an install button

**Comment by JDOG787** [comment]
Yea, i will probs help with parts of this

**Comment by CoolCoderSJ** [comment]
@JDOG787 if u want to help...do u know sqlite3?

i need a bit of help with that, other than that i dont think theres really much left...

**Comment by CoolCoderSJ** [comment]
- Seems like webpage is back up with db and api, for notes the API endpoint is


https://reflux-marketplace.coolcodersj.repl.co/api
This will return a list. The list has 1 dictionary for each verified theme.
Each dictionary has the following components - 
```
user: The repl owner
name: Theme name
desc: Theme description
code-jswa: Theme code. JS code with alert
code-jswoa: If an admin has provided JS code without alert, it will show here.
```

**Comment by CoolCoderSJ** [comment]
we have run into a tiny problem while integrating this....due to default non-toggle-able CORS on webpy, we will either have to mix in express for the api, or switch to mongodb.

Id rather switch to mongo, if anyone with mongo experience wants to help with that.

**Comment by whippingdot** [comment]
Close the issue guys

**Comment by spotandjake** [comment]
It is not done old you dont have to make comments on every single issue

**Comment by whippingdot** [comment]
ok sorry 😭 😭. Also you moved this from in-progress to done...
